export const AUDIT_SERVICE_CATALOG = [
  {
    id: "netflix",
    name: "Netflix",
    aliases: ["netflix", "netflix standard"],
    monthlyPrice: 15.49,
    category: "Streaming",
  },
  {
    id: "spotify",
    name: "Spotify Premium",
    aliases: ["spotify", "spotify premium"],
    monthlyPrice: 11.99,
    category: "Music",
  },
  {
    id: "youtube-premium",
    name: "YouTube Premium",
    aliases: ["youtube premium", "youtube"],
    monthlyPrice: 13.99,
    category: "Streaming",
  },
  {
    id: "apple-music",
    name: "Apple Music",
    aliases: ["apple music"],
    monthlyPrice: 10.99,
    category: "Music",
  },
  {
    id: "chatgpt-plus",
    name: "ChatGPT Plus",
    aliases: ["chatgpt", "chatgpt plus"],
    monthlyPrice: 20,
    category: "AI Tools",
  },
  {
    id: "claude-pro",
    name: "Claude Pro",
    aliases: ["claude", "claude pro"],
    monthlyPrice: 20,
    category: "AI Tools",
  },
  {
    id: "adobe-creative-cloud",
    name: "Adobe Creative Cloud",
    aliases: ["adobe", "creative cloud", "adobe creative cloud"],
    monthlyPrice: 59.99,
    category: "Design",
  },
  {
    id: "figma-pro",
    name: "Figma Professional",
    aliases: ["figma", "figma professional", "figma pro"],
    monthlyPrice: 15,
    category: "Design",
  },
  {
    id: "notion-plus",
    name: "Notion Plus",
    aliases: ["notion", "notion plus"],
    monthlyPrice: 12,
    category: "Productivity",
  },
  {
    id: "dropbox-plus",
    name: "Dropbox Plus",
    aliases: ["dropbox", "dropbox plus"],
    monthlyPrice: 11.99,
    category: "Storage",
  },
  {
    id: "google-one",
    name: "Google One",
    aliases: ["google one"],
    monthlyPrice: 9.99,
    category: "Storage",
  },
  {
    id: "icloud-plus",
    name: "iCloud+",
    aliases: ["icloud", "icloud+"],
    monthlyPrice: 9.99,
    category: "Storage",
  },
  {
    id: "amazon-prime",
    name: "Amazon Prime",
    aliases: ["prime", "amazon prime"],
    annualPrice: 139,
    category: "Shopping",
  },
  {
    id: "disney-plus",
    name: "Disney+",
    aliases: ["disney", "disney+"],
    monthlyPrice: 15.99,
    category: "Streaming",
  },
  {
    id: "hulu",
    name: "Hulu",
    aliases: ["hulu"],
    monthlyPrice: 9.99,
    category: "Streaming",
  },
  {
    id: "max",
    name: "Max",
    aliases: ["max", "hbo max"],
    monthlyPrice: 16.99,
    category: "Streaming",
  },
  {
    id: "duolingo-max",
    name: "Duolingo Max",
    aliases: ["duolingo", "duolingo max"],
    monthlyPrice: 29.99,
    category: "Learning",
  },
  {
    id: "headspace",
    name: "Headspace",
    aliases: ["headspace"],
    annualPrice: 69.99,
    category: "Wellness",
  },
  {
    id: "calm",
    name: "Calm",
    aliases: ["calm"],
    annualPrice: 69.99,
    category: "Wellness",
  },
  {
    id: "strava",
    name: "Strava",
    aliases: ["strava"],
    annualPrice: 79.99,
    category: "Fitness",
  },
]
